server:
  port: ${SERVER_PORT:8000}    #default port where the service will be started
spring:
  application:
    name: zuul   #current service name to be used by the eureka server
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://192.168.1.10:9090/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
zuul:
  routes:
    productpage:
      path: /productpage/**
      serviceId: productpage
      stripPrefix: false
    webjars:
      path: /webjars/**
      serviceId: productpage
      stripPrefix: false
    details:
      path: /details/**
      serviceId: details
      stripPrefix: false
    reviews:
      path: /reviews/**
      serviceId: reviews
      stripPrefix: false
    ratings:
      path: /ratings/**
      serviceId: ratings
      stripPrefix: false
ribbon:
  eureka:
    enabled: true

