server:
  port: ${PORT:9090} # Indicate the default PORT where this service will be started
spring:
  application:
    name: eureka
eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
