server:
  port: ${SERVER_PORT:8093}    #default port where the service will be started
spring:
  application:
    name: reviews   #current service name to be used by the eureka server
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

feign:
  client:
    config:
      ratings:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

ribbon:
  eureka:
    enabled: true

enable_ratings: ${ENABLE_RATINGS:true}
star_color: ${STAR_COLOR:black}

