server:
  port: 8082    #default port where the service will be started
spring:
  application:
    name: reviews   #current service name to be used by the eureka server
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
