server:
  port: ${SERVER_PORT:8084}    #default port where the service will be started
spring:
  application:
    name: details   #current service name to be used by the eureka server
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
ribbon:
  eureka:
    enabled: true
